// Generated by dts-bundle-generator v6.11.0

export interface ITimeline {
	id: number;
	color: string;
	startAt: string;
	endAt: string;
	meta?: any;
}
declare class Timeline {
	id: number;
	color: string;
	startAt: Date;
	endAt: Date;
	meta?: any;
	constructor(data: ITimeline);
}
declare class Timetable {
	private rootElement;
	private hourElements;
	private timelines;
	private options;
	constructor(rootElement: HTMLElement, timelines?: ITimeline[], options?: {
		startHour: number;
	});
	private init;
	private draw;
	getTimelines(): Timeline[];
	addTimeline(_timeline: ITimeline): void;
	removeTimeline(id: number): void;
}

export {
	Timetable as default,
};

export as namespace MyTimetable;

export {};
