// Generated by dts-bundle-generator v6.11.0

declare class Timeline {
	id: number;
	color: string;
	startAt: Date;
	endAt: Date;
	meta?: any;
	constructor(id: number, color: string, startAt: Date, endAt: Date, meta?: any);
}
declare class Timetable {
	rootElement: HTMLElement;
	timelines: Timeline[];
	constructor(rootElement: HTMLElement, timelines: Timeline[]);
	init(): void;
}

export {
	Timetable as default,
};

export as namespace MyTimetable;

export {};
