// Generated by dts-bundle-generator v6.11.0

export interface ITimeline {
	id: number;
	color: string;
	startAt: string;
	endAt: string;
	meta?: any;
}
declare class Timeline {
	id: number;
	color: string;
	startAt: Date;
	endAt: Date;
	meta?: any;
	constructor(data: ITimeline);
}
declare class Timetable {
	rootElement: HTMLElement;
	hourElements: HTMLElement[];
	timelines: Timeline[];
	options: {
		startHour: number;
	};
	constructor(rootElement: HTMLElement, timelines: ITimeline[] | undefined, options: {
		startHour: number;
	});
	private init;
	private draw;
	addTimeline(_timeline: ITimeline): void;
	removeTimeline(id: number): void;
}

export {
	Timetable as default,
};

export as namespace MyTimetable;

export {};
