"use strict";
exports.__esModule = true;
exports.Timetable = void 0;
var Timetable = /** @class */ (function () {
    function Timetable(rootElement, timelines) {
        this.rootElement = rootElement;
        this.timelines = timelines;
        this.init();
    }
    Timetable.prototype.init = function () {
        this.rootElement.innerHTML = "<div class=\"timetable\">\n            <div class=\"hours hour-header\">\n                <div class=\"hour\">0</div>\n                <div class=\"hour\">1</div>\n                <div class=\"hour\">2</div>\n                <div class=\"hour\">3</div>\n                <div class=\"hour\">4</div>\n                <div class=\"hour\">5</div>\n                <div class=\"hour\">6</div>\n                <div class=\"hour\">7</div>\n                <div class=\"hour\">8</div>\n                <div class=\"hour\">9</div>\n                <div class=\"hour\">10</div>\n                <div class=\"hour\">11</div>\n                <div class=\"hour\">12</div>\n                <div class=\"hour\">13</div>\n                <div class=\"hour\">14</div>\n                <div class=\"hour\">15</div>\n                <div class=\"hour\">16</div>\n                <div class=\"hour\">17</div>\n                <div class=\"hour\">18</div>\n                <div class=\"hour\">19</div>\n                <div class=\"hour\">20</div>\n                <div class=\"hour\">21</div>\n                <div class=\"hour\">22</div>\n                <div class=\"hour\">23</div>\n            </div>\n            <div class=\"contents\">\n                <div class=\"minutes\">\n                    <div class=\"minute minute-0\">0</div>\n                    <div class=\"minute minute-10\">10</div>\n                    <div class=\"minute minute-20\">20</div>\n                    <div class=\"minute minute-30\">30</div>\n                    <div class=\"minute minute-40\">40</div>\n                    <div class=\"minute minute-50\">50</div>\n                </div>\n                <div class=\"hours\">\n                    <div class=\"hour\">0</div>\n                    <div class=\"hour\">1</div>\n                    <div class=\"hour\">2</div>\n                    <div class=\"hour\">3</div>\n                    <div class=\"hour\">4</div>\n                    <div class=\"hour\">5</div>\n                    <div class=\"hour\">6</div>\n                    <div class=\"hour\">7</div>\n                    <div class=\"hour\">8</div>\n                    <div class=\"hour\">9</div>\n                    <div class=\"hour\">10</div>\n                    <div class=\"hour\">11</div>\n                    <div class=\"hour\">12</div>\n                    <div class=\"hour\">13</div>\n                    <div class=\"hour\">14</div>\n                    <div class=\"hour\">15</div>\n                    <div class=\"hour\">16</div>\n                    <div class=\"hour\">17</div>\n                    <div class=\"hour\">18</div>\n                    <div class=\"hour\">19</div>\n                    <div class=\"hour\">20</div>\n                    <div class=\"hour\">21</div>\n                    <div class=\"hour\">22</div>\n                    <div class=\"hour\">23</div>\n                </div>\n            </div>\n        </div>";
    };
    return Timetable;
}());
exports.Timetable = Timetable;
